import React, { useState } from "react";
import {
  SandpackProvider,
  SandpackConsole,
  SandpackPreview,
  SandpackLayout,
  DirectoryIconClosed,
} from "@codesandbox/sandpack-react";

import { SandpackFileExplorer } from "sandpack-file-explorer";

import Editor from "@monaco-editor/react";

import MonacoEditor from "./MonacoEditor";
import ToolBar from "./components/auth/ToolBar";

export default function Playground() {
  const [customSetup, setCustomSetup] = useState({});

  const files = {
    "/index.html": {
      code: `<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n        <title>React Essentials</title>\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"/src/index.jsx\"></script>\n  </body>\n</html>\n`,
    },
    "/src/App.jsx": {
      code: `function App() {\n  return (\n    <div>\n      <header>\n        <img src=\"src/assets/react-core-concepts.png\" alt=\"Stylized atom\" />\n        <h1>React Essentials</h1>\n        <p>\n          Fundamental React concepts you will need for almost any app you are\n          going to build!\n        </p>\n      </header>\n      <main>\n        <h2>Time to get started!</h2>\n      </main>\n    </div>\n  );\n}\n\nexport default App;\n`,
    },
    "/src/index.jsx": {
      code: `import ReactDOM from \"react-dom/client\";\n\nimport App from \"./App.jsx\";  \n\nconst entryPoint = document.getElementById(\"root\");\nReactDOM.createRoot(entryPoint).render(<App />);\n`,
    },
  };
  const s = {
    entry: "/src/index.jsx",
    environment: "create-react-app",
    dependencies: {
      react: "^18.0.0",
      "react-dom": "^18.0.0",
    },
    files,
  };

  const customSetup1 = {
    entry: "index.js",
    dependencies: {
      "react-markdown": "latest",
    },
  };
  const files1 = {
    "/App.js": `import React from "react"; 

export default function App() {
return (
<div>
<h2>Hello Test</h2>
</div>
);
}

`,
  };

  const vfiles = {
    "/index.js": {
      code: "// index.js",
      active: true,
    },
    "/index2.js": {
      code: "// index2.js",
    },
    "/src/index.js": {
      code: "// this file is generated by vanilla template, but it is not needed",
      hidden: true,
    },
    "/hidden.js": {
      code: "// hidden.js",
      hidden: true,
    },
  };
  return (
    <SandpackProvider
      customSetup={{
        entry: "/src/index.jsx",
        dependencies: {
          react: "^18.0.0",
          "react-dom": "^18.0.0",
        },
      }}
      files={files}
    >
      <SandpackLayout
        style={{
          display: "flex",
        }}
      >
        <SandpackFileExplorer />

        <MonacoEditor />

        <div
          style={{ display: "flex", flexDirection: "column", width: "30vw" }}
        >
          <ToolBar setCustomSetup={setCustomSetup} />
          <SandpackPreview
            style={{
              border: "1px solid #339af0",
              height: "50vh",
              width: "100%",
            }}
          />
          <SandpackConsole
            style={{
              border: "1px solid #fcc419",
              height: "30vh",
              width: "100%",
            }}
          />
        </div>
      </SandpackLayout>
    </SandpackProvider>
  );
}
